#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 23, 2019 01:49:49 PM CET  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global Checkbutton1_Var
    Checkbutton1_Var = tk.IntVar()
    Checkbutton1_Var.set(1)
    global Checkbutton2_Var
    Checkbutton2_Var = tk.IntVar()
    Checkbutton2_Var.set(1)
    global Checkbutton3_Var
    Checkbutton3_Var = tk.IntVar()
    #Checkbutton3_Var.set(1)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Main_Window
    Main_Window.vp_start_gui()




